### ISSUE TITLE
Poor performance when executing SaveClients() method in Database.cs

### ISSUE THREAD

**Issue by DragonZero** [ThomasVieth/Warcraft-Source-2#2]
The examples for Counterstrikesharp API, indicate that any database connections should be executed under a separate thread, so as not to block the main game thread.  https://docs.cssharp.dev/examples/WithDatabase.html

I am running a virtual machine for my dedicated server, IOPS are not the best even though the host is running NVME drives.  When the 60 second loop hits and all active players are saved to the database, there is a significant hit to the performance of the game being run.  And all players connected will lag out for 2 to 3 seconds.

All other database queries are singletons and I don't believe need any modifications at this point.  But the SaveClients() method has several queries that need to happen, and with SqlLite, the recommendation is to wrap multiple queries into a transaction, to make a single write to the disk (instead of multiple writes, 1 for each query).  

I have modified the Database.cs file in my environment by wrapping these queries in a transaction.  Reach out if you wish to see my changes.  Not sure how to create a pull request.

**Comment by ThomasVieth** [comment]
Added as of version 2.3.0
