### ISSUE TITLE
Ultimate ability works during the few second freeze time just before the round starts

### ISSUE THREAD

**Issue by DragonZero** [ThomasVieth/Warcraft-Source-2#3]
While waiting for the round to start, just after purchasing a gun, the ultimate ability is available.  Human Alliance: teleport will push the player forward.

**Comment by ThomasVieth** [comment]
![image](https://github.com/ThomasVieth/Warcraft-Source-2/assets/8157465/8d113cb2-c5ea-4b53-90e0-a31ae0bc0b04)

https://github.com/ThomasVieth/Warcraft-Source-2/commit/1e6ef7438c9d6e7c83b8f092f5d69dc419d03dba

Take a look at the new implementation for cooldowns :) once I have updated the other races to use this, we should be able to close this. Lemme know if you think I need to add functionality or change something to resolve this problem further.
